version: '3.8'

services:
  web:
    image: docker.arvancloud.ir/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html:ro
      - ./style.css:/usr/share/nginx/html:ro
      - ./img:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
