version: '3.8'

services:
  web:
    image: docker.arvancloud.ir/nginx:latest
    ports:
      - "9000:9000"
    volumes:
      - ./index.html:/usr/share/nginx/html:ro
      - ./style:/usr/share/nginx/html:ro
      - ./img:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
